site_name: Anremithrlâ€™s Guide to Earendor
site_url: https://augustin007.github.io/anremithrl-s-guide-to-earendor/

docs_dir: guide-to-earendor
site_dir: site

theme:
  name: material
  locale: en
  color_mode: dark
  nav_style: light
  shortcuts:
    next: 78
    previous: 80
    search: 83
  navigation_depth: 4

plugins:
  - search

markdown_extensions:
  - footnotes
  - tables
  - admonition
  - toc:
      permalink: true

